spring:
  application:
    name: product-service

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8301/eureka/
#  instance:
#    hostname: localhost
#
#spring:
#  application:
#    name: product-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://ims-discovery-server.herokuapp.com/eureka/
  instance:
    hostname: ims-discovery-server.herokuapp.com
    homePageUrl: https://ims-product-service.herokuapp.com/
    statusPageUrl: https://ims-product-service.herokuapp.com/actuator/info
    healthCheckUrl: https://ims-product-service.herokuapp.com/actuator/health